# Workflow-3
name: Custom Greeting In Python
on:
  push:
    branches:
      - main
jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Script
        run: |
          
          chmod 700 script.py
          ./script.py

# Workflow-2
# name: Python Tests
# on:
#   push:
#     branches:
#       - main
#   pull_request:
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.x'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest pytest-cov
#       - name: Run tests with coverage
#         run: |
#           pytest --cov=script --cov-report=term-missing
# Workflow-1
# name: Python Linting Workflow
# on:
#   push:
#     branches:
#       - main 
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.x'
#       - name: Install flake8
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8
#       - name: Run flake8 linting
#         run: |
#           flake8 script.py --max-line-length=88
